name: docker-compose

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["optuna-210", "optuna-300", "optuna-301", "optuna-latest"]

    steps:
      - uses: actions/checkout@v2

      - name: start storage servers
        run: |
          docker compose up -d mysql postgresql redis mssql

      - name: build
        run: |
          docker compose build ${{ matrix.version }}

      - name: run
        run: |
          docker compose run --rm ${{ matrix.version }} python src/init.py
          docker compose run --rm ${{ matrix.version }} bash src/upgrade.sh
          docker compose run --rm ${{ matrix.version }} bash src/redis/upgrade.sh
          docker compose run --rm ${{ matrix.version }} python src/load.py
